### ISSUE TITLE
The precision with batch inference is not as good as when trained

### ISSUE THREAD

**Issue by mugenggeng** [Echo0125/Memory-and-Anticipation-Transformer#14]
Sorry to bother you, I recently had a problem with the batch test model: the accuracy obtained with the batch test was not as good as the test accuracy obtained during training. Do you know why?

**Comment by Echo0125** [comment]
Referring to line 53 in the dataset [perframe_data_layer.py](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/main/src/rekognition_online_action_detection/datasets/perframe_data_layers.py#L53), the data is sparsely sampled during training, including train data and val data, so the performance will be different from the final test.

**Comment by mugenggeng** [comment]
Thank you very much for your answer. Could you please provide us with the config file of HDD data set? @Echo0125

**Comment by Echo0125** [comment]
You can use the model parameters in [thumos' config](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/main/configs/THUMOS/MAT/mat_long_256_work_8_kinetics_1x.yaml) as hyperparameters. In addition, you can refer to the relevant hyperparameters mentioned in the [supplementary material](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Wang_Memory-and-Anticipation_Transformer_for_Online_Action_Understanding_ICCV_2023_supplemental.pdf) for modification.

**Comment by mugenggeng** [comment]
Thanks for your help, I also find that there seems to be no way to read HDD datasets in perframe_data_layers.py @Echo0125

**Comment by Echo0125** [comment]
You can prepare the dataset according to [this link](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/issues/12#issuecomment-2047856366).

**Comment by Prism-hua** [comment]
Hello @Echo0125 , I have downloaded the HDD dataset and found the folder of sensor features, but I do not know what kind of input type the sensor features belong to, rgb or optical flow? Because I have found only one folder, in contrast with the data structure of TVSeries mentioned in the [README](https://github.com/Echo0125/Memory-and-Anticipation-Transformer#:~:text=rgb_kinetics_resnet50/%0A%20%20%20%7C%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20Breaking_Bad_ep1.npy%20(of%20size%20L%20x%202048)%0A%20%20%20%E2%94%82%C2%A0%C2%A0%20%E2%94%9C%E2%94%80%E2%94%80%20...%0A%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20flow_kinetics_bninception/%0A%20%20%20%7C%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20Breaking_Bad_ep1.npy%20(of%20size%20L%20x%201024)%0A%20%20%20%7C%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20...%0A%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20target_perframe/%0A%20%20%20%7C%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20Breaking_Bad_ep1.npy%20(of%20size%20L%20x%2031)), which contains two separate folders for rgb inputs and optical flow inputs respectively.

Here is all the files I get after applied for the HDD dataset:
![image](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/assets/103121022/5d93b7a1-cffc-4f5a-a307-7f7168760bac)

**Comment by mugenggeng** [comment]
![image](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/assets/87792372/39ab26c9-740e-4eba-a259-383742f016b2)
I am very sorry to bother you again, but I would like to know how the data in Table 8 was obtained. Is there a script that can be run directly?

**Comment by Echo0125** [comment]
Sorry for the late reply. For parameters other than the Model, we referred to the previous papers. As for the Model, you can manually write a for-loop script to perform the necessary calculations.
