### ISSUE TITLE
Some questions about papers.

### ISSUE THREAD

**Issue by chcchc97** [Echo0125/Memory-and-Anticipation-Transformer#6]
Thank you for your excellent work! I would like to ask a question about the paper.
As section 5.3 Future Queries Renewal outline, "renewing times = 0” denotes no renewal and utilizes FA. I think renewing times = 1 denotes replacing the FA with Q'f. But what is the meaning of  renewing times = 2 ? Is it the same as the one shown in the picture below?
![image](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/assets/60684460/6f728463-d42c-453c-8cc4-1f0c9e6d33df)

**Comment by Echo0125** [comment]
Not entirely. When renewing times = 2, $\hat{M}_s$ will also be used as query again to cross attention the whole temporal context.

**Comment by chcchc97** [comment]
Thank you for your reply. I've got it!

**Comment by Chenhongchang** [comment]
I have another question about the feature extraction. Because I want to  apply mat to other datasets, so I try to extract the features by myself. As section 5.2 Implementation details, "extract the frames at 4 FPS for training and validation". I have resample the videos at 24 FPS and extract RGB and flow(视频帧和光流) using [[mmaction2().]()](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md) But I don't know how to set the video chunk size to 6. Are there any tools in mmaction2 can help to realize this step?

**Comment by Prism-hua** [comment]
> Not entirely. When renewing times = 2, M^s will also be used as query again to cross attention the whole temporal context.

Could you please futher explain this process again in a more detailed way?I am afraid that I can't understand about $M_{s}$ and $Q_{F}'$
